/*
 * This Spock specification was generated by the Gradle 'init' task.
 */
package ApprovalTests.Groovy.StarterProject

import org.approvaltests.Approvals
import org.junit.jupiter.api.Assertions
import org.junit.jupiter.api.Test
import spock.lang.Specification

class AppTest extends Specification {
    @Test
    void testNormalJUnit() {
        Assertions.assertEquals(5, 5)
    }
    @Test
    void testWithApprovalTests() {
        Approvals.verify("Hello World")
    }
    
    def "Approvals does not support Spock"() {
        setup:
        def app = new App()

        when:
        def result = app.greeting

        then:
        result == "Hello Approvals!"
//        Approvals.verify("Hello World")  // not currently supported
    }
}
