/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package ApprovalTests.Groovy.StarterProject

class App {
    String getGreeting() {
        return 'Hello Approvals!'
    }

    static void main(String[] args) {
        println new App().greeting
    }
}
