
name: build_and_test

on:
  push:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2.1.3
      - name: run_tests
        run: ./run_tests.sh
